[package]
name = "send_file"
version = "0.1.0"
authors = ["Thomas de Zeeuw <thomasdezeeuw@gmail.com>"]
edition = "2018"
build = "build.rs"

[dependencies]
libc = "0.2.44"
log  = "0.4.6"

[dev-dependencies]
futures-test-preview = "0.3.0-alpha.16"
